// packages/angular/@examples/standard/src/app/pages/components/skeleton/skeleton.ts
import { Component } from '@angular/core';
import { HlmSkeleton } from '@egose/shadcn-theme-ng/skeleton';

@Component({
  selector: 'app-skeleton-page',
  imports: [HlmSkeleton],
  template: `
    <h3 class="tw:text-2xl tw:font-bold tw:mb-2">Skeleton</h3>
    <p class="tw:text-gray-500 tw:mb-4">A placeholder for loading content.</p>
    <div class="tw:flex tw:items-center tw:gap-4">
      <hlm-skeleton class="tw:h-12 tw:w-12 tw:rounded-full" />
      <div class="tw:flex tw:flex-col tw:gap-2">
        <hlm-skeleton class="tw:h-4 tw:w-[250px]" />
        <hlm-skeleton class="tw:h-4 tw:w-[200px]" />
      </div>
    </div>
  `,
})
export class SkeletonPage {}

// packages/react/@examples/nextjs/components/showcases/components/skeleton.tsx
import { ExamplePage, ExampleSection } from '@/components/showcase-shell';
import { Skeleton } from '@egose/shadcn-theme/components/ui/skeleton';

export default function SkeletonShowcase() {
  return (
    <ExamplePage
      title="Skeleton"
      description="Skeleton placeholders reduce perceived waiting time while data is loading."
    >
      <ExampleSection title="Card placeholder">
        <div className="space-y-3 rounded-xl border p-4">
          <Skeleton className="h-5 w-40" />
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-5/6" />
          <div className="flex items-center gap-3 pt-2">
            <Skeleton className="size-10 rounded-full" />
            <div className="space-y-2">
              <Skeleton className="h-4 w-28" />
              <Skeleton className="h-3 w-20" />
            </div>
          </div>
        </div>
      </ExampleSection>
    </ExamplePage>
  );
}
