// packages/react/@examples/nextjs/app/components/sheet/page.tsx
'use client';

import { Button } from '../../../../../components/ui/button';
import { Input } from '../../../../../components/ui/input';
import { Label } from '../../../../../components/ui/label';
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from '../../../../../components/ui/sheet';

export default function Page() {
  return (
    <Sheet>
      <SheetTrigger asChild>
        <Button variant="outline">Open</Button>
      </SheetTrigger>
      <SheetContent>
        <SheetHeader>
          <SheetTitle>Edit profile</SheetTitle>
          <SheetDescription>Make changes to your profile here. Click save when you&apos;re done.</SheetDescription>
        </SheetHeader>
        <div className="grid flex-1 auto-rows-min gap-6 px-4">
          <div className="grid gap-3">
            <Label htmlFor="sheet-demo-name">Name</Label>
            <Input id="sheet-demo-name" defaultValue="Pedro Duarte" />
          </div>
          <div className="grid gap-3">
            <Label htmlFor="sheet-demo-username">Username</Label>
            <Input id="sheet-demo-username" defaultValue="@peduarte" />
          </div>
        </div>
        <SheetFooter>
          <Button type="submit">Save changes</Button>
          <SheetClose asChild>
            <Button variant="outline">Close</Button>
          </SheetClose>
        </SheetFooter>
      </SheetContent>
    </Sheet>
  );
}

// packages/angular/@examples/standard/src/app/pages/components/form-field/sheet.ts
import { Component } from '@angular/core';
import { provideIcons } from '@ng-icons/core';
import { lucideCross } from '@ng-icons/lucide';
import { BrnSheetImports } from '@spartan-ng/brain/sheet';
import { HlmButtonImports } from '@egose/shadcn-theme-ng/button';
import { HlmLabelImports } from '@egose/shadcn-theme-ng/label';
import { HlmSheetImports } from '@egose/shadcn-theme-ng/sheet';

@Component({
  selector: 'sheet-example',
  imports: [BrnSheetImports, HlmSheetImports, HlmButtonImports, HlmLabelImports],
  providers: [provideIcons({ lucideCross })],
  template: `
    <hlm-sheet side="right">
      <button id="edit-profile" variant="primary" brnSheetTrigger hlmButton>Open</button>
      <hlm-sheet-content *brnSheetContent="let ctx">
        <hlm-sheet-header>
          <h3 hlmSheetTitle>Edit Profile</h3>
          <p hlmSheetDescription>Make changes to your profile here. Click save when you're done.</p>
        </hlm-sheet-header>
        <div class="tw:grid tw:flex-1 tw:auto-rows-min tw:gap-6 tw:px-4">
          <div class="tw:grid tw:gap-3">Grid 1</div>
          <div class="tw:grid tw:gap-3">Grid 2</div>
        </div>
        <hlm-sheet-footer>
          <button hlmButton type="submit">Save Changes</button>
          <button brnSheetClose hlmButton variant="secondary" appearance="outline">Close</button>
        </hlm-sheet-footer>
      </hlm-sheet-content>
    </hlm-sheet>
  `,
})
export class SheetExample {}
