// packages/angular/projects/alert/src/lib/alert.ts
import { Directive, computed, input } from '@angular/core';
import { hlm } from '@egose/shadcn-theme-ng/utils';
import { type VariantProps, cva } from 'class-variance-authority';
import type { ClassValue } from 'clsx';

const alertVariants = cva(
  'tw:relative tw:w-full tw:items-start tw:gap-y-0.5 tw:rounded-lg tw:border tw:px-4 tw:py-3 tw:text-sm tw:has-[>[hlmAlertIcon]]:grid tw:has-[>[hlmAlertIcon]]:grid-cols-[calc(theme(spacing.1)*4)_1fr] tw:has-[>[hlmAlertIcon]]:gap-x-3 tw:[&>[hlmAlertIcon]]:size-4 tw:[&>[hlmAlertIcon]]:translate-y-0.5 tw:[&>[hlmAlertIcon]]:text-current',
  {
    variants: {
      variant: {
        primary: 'tw:bg-primary tw:text-primary-foreground tw:[&>[hlmAlertDescription]]:text-primary-foreground/90',
        secondary:
          'tw:bg-secondary tw:text-secondary-foreground tw:[&>[hlmAlertDescription]]:text-secondary-foreground/90',
        success: 'tw:bg-success tw:text-success-foreground tw:[&>[hlmAlertDescription]]:text-success-foreground/90',
        warning: 'tw:bg-warning tw:text-warning-foreground tw:[&>[hlmAlertDescription]]:text-warning-foreground/90',
        danger: 'tw:bg-danger tw:text-danger-foreground tw:[&>[hlmAlertDescription]]:text-danger-foreground/90',
        info: 'tw:bg-info tw:text-info-foreground tw:[&>[hlmAlertDescription]]:text-info-foreground/90',
        light: 'tw:bg-light tw:text-light-foreground tw:[&>[hlmAlertDescription]]:text-light-foreground/90',
        dark: 'tw:bg-dark tw:text-dark-foreground tw:[&>[hlmAlertDescription]]:text-dark-foreground/90',
        accent: 'tw:bg-accent tw:text-accent-foreground tw:[&>[hlmAlertDescription]]:text-accent-foreground/90',
        destructive:
          'tw:bg-destructive tw:text-destructive-foreground tw:[&>[hlmAlertDescription]]:text-destructive-foreground/90',
        muted: 'tw:bg-muted tw:text-muted-foreground tw:[&>[hlmAlertDescription]]:text-muted-foreground/90',
        link: 'tw:text-primary tw:underline-offset-4 tw:[&>[hlmAlertDescription]]:text-primary/90',
        ghost: 'tw:[&>[hlmAlertDescription]]:text-muted-foreground',
      },
      appearance: {
        solid: '',
        light: 'tw:font-semibold',
      },
    },
    compoundVariants: [
      {
        variant: 'primary',
        appearance: 'light',
        class: 'tw:bg-primary/20 tw:text-primary tw:[&>[hlmAlertDescription]]:text-primary',
      },
      {
        variant: 'secondary',
        appearance: 'light',
        class: 'tw:bg-secondary/20 tw:text-secondary tw:[&>[hlmAlertDescription]]:text-secondary',
      },
      {
        variant: 'success',
        appearance: 'light',
        class: 'tw:bg-success/20 tw:text-success tw:[&>[hlmAlertDescription]]:text-success',
      },
      {
        variant: 'warning',
        appearance: 'light',
        class: 'tw:bg-warning/20 tw:text-warning tw:[&>[hlmAlertDescription]]:text-warning',
      },
      {
        variant: 'danger',
        appearance: 'light',
        class: 'tw:bg-danger/20 tw:text-danger tw:[&>[hlmAlertDescription]]:text-danger',
      },
      {
        variant: 'info',
        appearance: 'light',
        class: 'tw:bg-info/20 tw:text-info tw:[&>[hlmAlertDescription]]:text-info',
      },
      {
        variant: 'light',
        appearance: 'light',
        class: 'tw:bg-light/20 tw:text-light tw:[&>[hlmAlertDescription]]:text-light',
      },
      {
        variant: 'dark',
        appearance: 'light',
        class: 'tw:bg-dark/20 tw:text-dark tw:[&>[hlmAlertDescription]]:text-dark',
      },
      {
        variant: 'accent',
        appearance: 'light',
        class: 'tw:bg-accent/20 tw:text-accent tw:[&>[hlmAlertDescription]]:text-accent',
      },
      {
        variant: 'destructive',
        appearance: 'light',
        class: 'tw:bg-destructive/20 tw:text-destructive tw:[&>[hlmAlertDescription]]:text-destructive',
      },
      {
        variant: 'muted',
        appearance: 'light',
        class: 'tw:bg-muted/20 tw:text-muted tw:[&>[hlmAlertDescription]]:text-muted',
      },
      {
        variant: 'link',
        appearance: 'light',
        class: 'tw:bg-primary/10 tw:text-primary tw:[&>[hlmAlertDescription]]:text-primary',
      },
      {
        variant: 'ghost',
        appearance: 'light',
        class: 'tw:bg-muted/10 tw:text-muted-foreground tw:[&>[hlmAlertDescription]]:text-muted-foreground',
      },
    ],
    defaultVariants: {
      variant: 'primary',
      appearance: 'solid',
    },
  },
);
export type AlertVariants = VariantProps<typeof alertVariants>;
export type VariantType = NonNullable<AlertVariants['variant']>;
export type AppearanceType = NonNullable<AlertVariants['appearance']>;
@Directive({
  selector: '[hlmAlert]',
  host: {
    role: 'alert',
    '[class]': '_computedClass()',
  },
})
export class HlmAlert {
  public readonly userClass = input<ClassValue>('', { alias: 'class' });
  public readonly variant = input<AlertVariants['variant']>('primary');
  public readonly appearance = input<AlertVariants['appearance']>('solid');
  protected readonly _computedClass = computed(() =>
    hlm(
      alertVariants({
        variant: this.variant(),
        appearance: this.appearance(),
      }),
      this.userClass(),
    ),
  );
}

// packages/react/components/ui/alert.tsx
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/ui';

const alertVariants = cva(
  'relative w-full items-start gap-y-0.5 rounded-lg border px-4 py-3 text-sm ' +
    '[&>svg+div]:translate-y-[-3px] ' +
    '[&>svg]:absolute [&>svg]:left-4 [&>svg]:top-2 [&>svg]:text-current ' +
    '[&>svg~*]:pl-7',
  {
    variants: {
      variant: {
        primary: 'bg-primary text-primary-foreground [&_[data-alert-description]]:text-primary-foreground/90',
        secondary: 'bg-secondary text-secondary-foreground [&_[data-alert-description]]:text-secondary-foreground/90',
        success: 'bg-success text-success-foreground [&_[data-alert-description]]:text-success-foreground/90',
        warning: 'bg-warning text-warning-foreground [&_[data-alert-description]]:text-warning-foreground/90',
        danger: 'bg-danger text-danger-foreground [&_[data-alert-description]]:text-danger-foreground/90',
        info: 'bg-info text-info-foreground [&_[data-alert-description]]:text-info-foreground/90',
        light: 'bg-light text-light-foreground [&_[data-alert-description]]:text-light-foreground/90',
        dark: 'bg-dark text-dark-foreground [&_[data-alert-description]]:text-dark-foreground/90',
        accent: 'bg-accent text-accent-foreground [&_[data-alert-description]]:text-accent-foreground/90',
        destructive:
          'bg-destructive text-destructive-foreground [&_[data-alert-description]]:text-destructive-foreground/90',
        muted: 'bg-muted text-muted-foreground [&_[data-alert-description]]:text-muted-foreground/90',
        link: 'text-primary underline-offset-4 [&_[data-alert-description]]:text-primary/90',
        ghost: '[&_[data-alert-description]]:text-muted-foreground',
      },
      appearance: {
        solid: '',
        light: 'font-semibold',
      },
    },
    compoundVariants: [
      {
        variant: 'primary',
        appearance: 'light',
        class: 'bg-primary/20 text-primary [&_[data-alert-description]]:text-primary',
      },
      {
        variant: 'secondary',
        appearance: 'light',
        class: 'bg-secondary/20 text-secondary [&_[data-alert-description]]:text-secondary',
      },
      {
        variant: 'success',
        appearance: 'light',
        class: 'bg-success/20 text-success [&_[data-alert-description]]:text-success',
      },
      {
        variant: 'warning',
        appearance: 'light',
        class: 'bg-warning/20 text-warning [&_[data-alert-description]]:text-warning',
      },
      {
        variant: 'danger',
        appearance: 'light',
        class: 'bg-danger/20 text-danger [&_[data-alert-description]]:text-danger',
      },
      { variant: 'info', appearance: 'light', class: 'bg-info/20 text-info [&_[data-alert-description]]:text-info' },
      {
        variant: 'light',
        appearance: 'light',
        class: 'bg-light/20 text-light [&_[data-alert-description]]:text-light',
      },
      { variant: 'dark', appearance: 'light', class: 'bg-dark/20 text-dark [&_[data-alert-description]]:text-dark' },
      {
        variant: 'accent',
        appearance: 'light',
        class: 'bg-accent/20 text-accent [&_[data-alert-description]]:text-accent',
      },
      {
        variant: 'destructive',
        appearance: 'light',
        class: 'bg-destructive/20 text-destructive [&_[data-alert-description]]:text-destructive',
      },
      {
        variant: 'muted',
        appearance: 'light',
        class: 'bg-muted/20 text-muted [&_[data-alert-description]]:text-muted',
      },
      {
        variant: 'link',
        appearance: 'light',
        class: 'bg-primary/10 text-primary [&_[data-alert-description]]:text-primary',
      },
      {
        variant: 'ghost',
        appearance: 'light',
        class: 'bg-muted/10 text-muted-foreground [&_[data-alert-description]]:text-muted-foreground',
      },
    ],
    defaultVariants: {
      variant: 'primary',
      appearance: 'solid',
    },
  },
);

export interface AlertProps extends React.HTMLAttributes<HTMLDivElement>, VariantProps<typeof alertVariants> {}
export type VariantType = NonNullable<VariantProps<typeof alertVariants>['variant']>;

const Alert = React.forwardRef<HTMLDivElement, AlertProps>(({ className, variant, appearance, ...props }, ref) => (
  <div ref={ref} role="alert" className={cn(alertVariants({ variant, appearance }), className)} {...props} />
));
Alert.displayName = 'Alert';

const AlertTitle = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLHeadingElement>>(
  ({ className, ...props }, ref) => (
    <h5 ref={ref} className={cn('mb-1 font-semibold leading-none tracking-tight', className)} {...props} />
  ),
);
AlertTitle.displayName = 'AlertTitle';

const AlertDescription = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLParagraphElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      data-alert-description
      className={cn('font-medium text-sm [&_p]:leading-relaxed', className)}
      {...props}
    />
  ),
);
AlertDescription.displayName = 'AlertDescription';

export { Alert, AlertTitle, AlertDescription };
