// packages/angular/projects/basic-alert/src/lib/basic-alert.ts
import { Component, input } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideCircleAlert,
  lucideCircleCheck,
  lucideInfo,
  lucideBatteryWarning,
  lucideBell,
  lucideStar,
  lucideThumbsUp,
  lucideZap,
  lucideLink,
  lucideGhost,
} from '@ng-icons/lucide';
import {
  HlmAlert,
  HlmAlertIcon,
  HlmAlertTitle,
  HlmAlertDescription,
  type VariantType,
  type AppearanceType,
} from '@egose/shadcn-theme-ng/alert';
import { HlmIcon } from '@egose/shadcn-theme-ng/icon';

@Component({
  selector: 'eg-basic-alert',
  standalone: true,
  imports: [HlmAlert, HlmAlertIcon, HlmAlertTitle, HlmAlertDescription, NgIcon, HlmIcon],
  providers: [
    provideIcons({
      lucideCircleCheck,
      lucideInfo,
      lucideBatteryWarning,
      lucideCircleAlert,
      lucideBell,
      lucideStar,
      lucideThumbsUp,
      lucideZap,
      lucideLink,
      lucideGhost,
    }),
  ],
  template: `
    <div hlmAlert [variant]="variant()" [appearance]="appearance()" class="">
      <ng-icon hlm hlmAlertIcon [name]="getIconName(variant())" />
      <h4 hlmAlertTitle class="tw:capitalize">{{ title() }}</h4>
      <p hlmAlertDescription>{{ description() }}</p>
    </div>
  `,
})
export class EgBasicAlert {
  variant = input<VariantType>('info');
  appearance = input<AppearanceType>('solid');
  title = input<string>('');
  description = input<string>('');

  getIconName(variant: VariantType): string {
    switch (variant) {
      case 'success':
        return 'lucideCircleCheck';
      case 'info':
        return 'lucideInfo';
      case 'warning':
        return 'lucideBatteryWarning';
      case 'danger':
      case 'destructive':
        return 'lucideCircleAlert';
      case 'muted':
        return 'lucideBell';
      case 'accent':
        return 'lucideStar';
      case 'primary':
        return 'lucideThumbsUp';
      case 'secondary':
        return 'lucideZap';
      case 'link':
        return 'lucideLink';
      case 'ghost':
        return 'lucideGhost';
      case 'light':
      case 'dark':
      default:
        return 'lucideInfo';
    }
  }
}

// packages/react/components/ui/basic-alert.tsx
import * as React from 'react';
import { Alert, AlertTitle, AlertDescription } from './alert';
import {
  IconCircleCheck,
  IconInfoCircle,
  IconBatteryExclamation,
  IconExclamationCircle,
  IconBell,
  IconStar,
  IconThumbUp,
  IconBolt,
  IconLink,
  IconGhost,
} from '@tabler/icons-react';
import type { AlertProps, VariantType } from './alert';

export interface BasicAlertProps extends Omit<AlertProps, 'children'> {
  variant?: VariantType;
  title: string;
  description?: string;
}

export const BasicAlert: React.FC<BasicAlertProps> = ({
  variant = 'primary',
  appearance = 'solid',
  title,
  description,
  ...props
}) => {
  return (
    <Alert variant={variant} appearance={appearance} {...props}>
      {getIcon(variant)}
      <AlertTitle className="capitalize">{title}</AlertTitle>
      {description && <AlertDescription>{description}</AlertDescription>}
    </Alert>
  );
};

function getIcon(variant: string) {
  switch (variant) {
    case 'success':
      return <IconCircleCheck className="size-5 translate-y-0.5 text-current" />;
    case 'info':
      return <IconInfoCircle className="size-5 translate-y-0.5 text-current" />;
    case 'warning':
      return <IconBatteryExclamation className="size-5 translate-y-0.5 text-current" />;
    case 'danger':
    case 'destructive':
      return <IconExclamationCircle className="size-5 translate-y-0.5 text-current" />;
    case 'muted':
      return <IconBell className="size-5 translate-y-0.5 text-current" />;
    case 'accent':
      return <IconStar className="size-5 translate-y-0.5 text-current" />;
    case 'primary':
      return <IconThumbUp className="size-5 translate-y-0.5 text-current" />;
    case 'secondary':
      return <IconBolt className="size-5 translate-y-0.5 text-current" />;
    case 'link':
      return <IconLink className="size-5 translate-y-0.5 text-current" />;
    case 'ghost':
      return <IconGhost className="size-5 translate-y-0.5 text-current" />;
    case 'light':
    case 'dark':
    default:
      return <IconInfoCircle className="size-5 translate-y-0.5 text-current" />;
  }
}
