// apps/angular/src/app/pages/components/button/button.ts
import { Component } from '@angular/core';
import { EgButton, AppearanceType, VariantType, SizeType } from '@egose/shadcn-theme-ng/button';
import { NgIcon } from '@ng-icons/core';
import { tablerBrandAngular } from '@ng-icons/tabler-icons';

@Component({
  selector: 'app-button',
  standalone: true,
  imports: [EgButton, NgIcon],
  template: `
    <h1 class="font-bold text-2xl mt-4 mb-5">Button</h1>

    <ng-template #iconTemplate>
      <ng-icon [svg]="icon" />
    </ng-template>

    @for (section of sections; track section.title) {
      <div class="font-semibold mt-4">
        <h3>{{ section.title }}</h3>
        <div class="flex flex-wrap gap-2">
          @for (v of variants; track v) {
            <button
              egBtn
              [variant]="v"
              [appearance]="section.appearance ?? 'solid'"
              [size]="section.size ?? 'default'"
              [disabled]="section.disabled || false"
              [loading]="section.loading || false"
              [icon]="section.icon ? iconTemplate : null"
              [iconPosition]="section.iconPosition || 'left'"
            >
              {{ v }}
            </button>
          }
        </div>
      </div>
    }
  `,
})
export class ButtonPage {
  icon = tablerBrandAngular;

  // Strongly typed variants
  variants: VariantType[] = [
    'primary',
    'secondary',
    'success',
    'warning',
    'danger',
    'info',
    'light',
    'dark',
    'link',
    'destructive',
    'accent',
    'muted',
  ];

  sections: {
    title: string;
    appearance?: AppearanceType;
    size?: SizeType;
    disabled?: boolean;
    loading?: boolean;
    icon?: boolean;
    iconPosition?: 'left' | 'right';
  }[] = [
    { title: 'Basic' },
    { title: 'Basic - disabled', disabled: true },
    { title: 'Basic - loading', loading: true },
    { title: 'Basic - disabled - loading', disabled: true, loading: true },
    { title: 'Basic - compact', size: 'compact-default' },

    { title: 'Outline', appearance: 'outline' },
    { title: 'Outline - disabled', appearance: 'outline', disabled: true },
    { title: 'Outline - loading', appearance: 'outline', loading: true },
    { title: 'Outline - disabled - loading', appearance: 'outline', disabled: true, loading: true },
    { title: 'Outline - compact', appearance: 'outline', size: 'compact-default' },

    { title: 'Outline filled', appearance: 'outlineFilled' },
    { title: 'Outline filled - disabled', appearance: 'outlineFilled', disabled: true },
    { title: 'Outline filled - loading', appearance: 'outlineFilled', loading: true },
    { title: 'Outline filled - disabled - loading', appearance: 'outlineFilled', disabled: true, loading: true },
    { title: 'Outline filled - compact', appearance: 'outlineFilled', size: 'compact-default' },

    { title: 'Icon (left)', icon: true, iconPosition: 'left' },
    { title: 'Icon (right)', icon: true, iconPosition: 'right' },
  ];
}

// apps/nextjs/app/components/button/page.tsx
'use client';

import { IconInbox } from '@tabler/icons-react';
import _startCase from 'lodash-es/startCase';
import { Button } from '../../../../../packages/react/components/ui/button';

const variants = [
  'primary',
  'secondary',
  'success',
  'warning',
  'danger',
  'info',
  'light',
  'dark',
  'link',
  'destructive',
  'accent',
  'muted',
] as const;

export default function Page() {
  return (
    <>
      <h1 className="font-bold text-2xl mt-4 mb-5">Button</h1>

      {/* Basic */}
      <Section title="Basic">
        {variants.map((variant) => (
          <Button key={variant} variant={variant}>
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Basic - disabled */}
      <Section title="Basic - disabled">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} disabled>
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Basic - loading */}
      <Section title="Basic - loading">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} loading>
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Basic - disabled + loading */}
      <Section title="Basic - disabled - loading">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} disabled loading>
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Compact (was thin) */}
      <Section title="Compact">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} size="compact-default">
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Outline */}
      <Section title="Outline">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} appearance="outline">
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Outline - disabled */}
      <Section title="Outline - disabled">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} appearance="outline" disabled>
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Outline - loading */}
      <Section title="Outline - loading">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} appearance="outline" loading>
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Outline - disabled + loading */}
      <Section title="Outline - disabled - loading">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} appearance="outline" disabled loading>
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Outline - compact */}
      <Section title="Outline - compact">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} appearance="outline" size="compact-default">
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Outline Filled */}
      <Section title="Outline filled">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} appearance="outlineFilled">
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Outline Filled - disabled */}
      <Section title="Outline filled - disabled">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} appearance="outlineFilled" disabled>
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Outline Filled - loading */}
      <Section title="Outline filled - loading">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} appearance="outlineFilled" loading>
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Outline Filled - disabled + loading */}
      <Section title="Outline filled - disabled - loading">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} appearance="outlineFilled" disabled loading>
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Outline Filled - compact */}
      <Section title="Outline filled - compact">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} appearance="outlineFilled" size="compact-default">
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      {/* Icons */}
      <Section title="Icon (left)">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} icon={<IconInbox />} iconPosition="left">
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      <Section title="Icon (right)">
        {variants.map((variant) => (
          <Button key={variant} variant={variant} icon={<IconInbox />} iconPosition="right">
            {_startCase(variant)}
          </Button>
        ))}
      </Section>
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="font-semibold mt-4">
      <h3>{title}</h3>
      <div className="flex flex-wrap gap-2">{children}</div>
    </div>
  );
}
