// packages/angular/@examples/standard/src/app/pages/components/resizable/resizable.ts
import { Component } from '@angular/core';
import { DemoHeaderComponent } from '../../../shared/demo-header';
import { DemoSectionComponent } from '../../../shared/demo-section';
import { BrnResizableGroup, BrnResizableHandle, BrnResizablePanel } from '@spartan-ng/brain/resizable';
import { HlmResizableImports } from '@egose/shadcn-theme-ng/resizable';

@Component({
  selector: 'app-resizable-page',
  imports: [
    DemoHeaderComponent,
    DemoSectionComponent,
    BrnResizableGroup,
    BrnResizableHandle,
    BrnResizablePanel,
    HlmResizableImports,
  ],
  template: `
    <app-demo-header title="Resizable" description="Draggable panels with horizontal and vertical layouts." />

    <div class="tw:grid tw:gap-6">
      <app-demo-section kicker="Horizontal" title="Two panels" description="Drag the handle to resize.">
        <div hlmResizableGroup class="tw:flex tw:h-[200px] tw:w-full tw:max-w-md tw:rounded-md tw:border">
          <div hlmResizablePanel class="tw:flex tw:items-center tw:justify-center tw:p-6">One</div>
          <hlm-resizable-handle />
          <div hlmResizablePanel class="tw:flex tw:items-center tw:justify-center tw:p-6">Two</div>
        </div>
      </app-demo-section>

      <app-demo-section kicker="Horizontal" title="Three panels" description="Two handles, three sections.">
        <div hlmResizableGroup class="tw:flex tw:h-[200px] tw:w-full tw:max-w-lg tw:rounded-md tw:border">
          <div hlmResizablePanel class="tw:flex tw:items-center tw:justify-center tw:p-6">Sidebar</div>
          <hlm-resizable-handle />
          <div hlmResizablePanel class="tw:flex tw:items-center tw:justify-center tw:p-6">Content</div>
          <hlm-resizable-handle />
          <div hlmResizablePanel class="tw:flex tw:items-center tw:justify-center tw:p-6">Inspector</div>
        </div>
      </app-demo-section>
    </div>
  `,
})
export class ResizablePage {}

// packages/react/@examples/nextjs/app/components/resizable/page.tsx
'use client';

import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from '@egose/shadcn-theme/components/ui/resizable';
import { ExamplePage, ExampleSection } from '@/components/showcase-shell';

export default function Page() {
  return (
    <ExamplePage title="Resizable" description="A layout primitive for panels that can be resized via drag handles.">
      <ExampleSection title="Nested Panels" description="Horizontal split with a vertically nested second panel.">
        <ResizablePanelGroup orientation="horizontal" className="max-w-sm rounded-lg border">
          <ResizablePanel defaultSize="50%">
            <div className="flex h-[200px] items-center justify-center p-6">
              <span className="font-semibold">One</span>
            </div>
          </ResizablePanel>
          <ResizableHandle withHandle />
          <ResizablePanel defaultSize="50%">
            <ResizablePanelGroup orientation="vertical">
              <ResizablePanel defaultSize="25%">
                <div className="flex h-full items-center justify-center p-6">
                  <span className="font-semibold">Two</span>
                </div>
              </ResizablePanel>
              <ResizableHandle withHandle />
              <ResizablePanel defaultSize="75%">
                <div className="flex h-full items-center justify-center p-6">
                  <span className="font-semibold">Three</span>
                </div>
              </ResizablePanel>
            </ResizablePanelGroup>
          </ResizablePanel>
        </ResizablePanelGroup>
      </ExampleSection>
    </ExamplePage>
  );
}
