// package/components/ui/button.tsx
import * as React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../lib/utils';
import { Spinner } from './spinner';

const buttonVariants = cva(
  [
    'cursor-pointer',
    'active:translate-y-[0.5px]',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
    'focus-visible:outline-none',
    'focus-visible:ring-1',
    'focus-visible:ring-ring',
    'font-medium',
    'gap-2',
    'inline-flex',
    'items-center',
    'justify-center',
    'rounded-sm',
    'text-sm',
    'transform',
    'transition',
    'transition-colors',
    'whitespace-nowrap',
    '[&_svg]:pointer-events-none',
    '[&_svg]:shrink-0',
    '[&_svg]:size-4',
  ],
  {
    variants: {
      variant: {
        primary: 'border border-primary bg-primary text-primary-foreground shadow-sm hover:bg-primary/90',
        secondary: 'border border-secondary bg-secondary text-secondary-foreground shadow-sm hover:bg-secondary/90',
        success: 'border border-success bg-success text-success-foreground shadow-sm hover:bg-success/90',
        warning: 'border border-warning bg-warning text-warning-foreground shadow-sm hover:bg-warning/90',
        danger: 'border border-danger bg-danger text-danger-foreground shadow-sm hover:bg-danger/90',
        info: 'border border-info bg-info text-info-foreground shadow-sm hover:bg-info/90',
        light: 'border border-light bg-light text-light-foreground shadow-sm hover:bg-light/90',
        dark: 'border border-dark bg-dark text-dark-foreground shadow-sm hover:bg-dark/90',
        accent: 'border border-accent bg-accent text-accent-foreground shadow-sm hover:bg-accent/90',
        destructive:
          'border border-destructive bg-destructive text-destructive-foreground shadow-sm hover:bg-destructive/90',
        muted: 'border border-muted bg-muted text-muted-foreground shadow-sm hover:bg-muted/90',
        link: 'text-primary underline-offset-4 hover:underline',
        ghost: 'hover:bg-light hover:text-light-foreground',
      },
      size: {
        default: 'h-9 px-4 py-2',
        sm: 'h-8 rounded-sm px-3 text-xs',
        lg: 'h-10 rounded-sm px-8',
        icon: 'h-9 w-9',
      },
      outline: {
        false: null,
        true: '',
      },
      outlineFilled: {
        false: null,
        true: '',
      },
      loading: {
        false: null,
        true: '',
      },
      thin: {
        false: null,
        true: '',
      },
    },
    defaultVariants: {
      variant: 'primary',
      size: 'default',
      outline: false,
      outlineFilled: false,
      loading: false,
      thin: false,
    },
  },
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
  left?: React.ReactNode;
}

function getOutlineClasses(variant: any) {
  const colors: Record<string, string> = {
    primary: 'border-primary text-primary shadow-sm hover:bg-primary/10',
    secondary: 'border-secondary text-secondary shadow-sm hover:bg-secondary/10',
    success: 'border-success text-success shadow-sm hover:bg-success/10',
    warning: 'border-warning text-warning shadow-sm hover:bg-warning/10',
    danger: 'border-danger text-danger shadow-sm hover:bg-danger/10',
    info: 'border-info text-info shadow-sm hover:bg-info/10',
    light: 'border-light text-light-foreground shadow-sm hover:bg-light/10',
    dark: 'border-dark text-dark shadow-sm hover:bg-dark/10',
    accent: 'border-accent text-accent shadow-sm hover:bg-accent/10',
    destructive: 'border-destructive text-destructive shadow-sm hover:bg-destructive/10',
    muted: 'border-muted text-muted-foreground shadow-sm hover:bg-muted/10',
  };

  return colors[variant ?? 'primary'];
}

function getOutlineFilledClasses(variant: any) {
  const colors: Record<string, string> = {
    primary: 'hover:bg-primary hover:text-primary-foreground',
    secondary: 'hover:bg-secondary hover:text-secondary-foreground',
    success: 'hover:bg-success hover:text-success-foreground',
    warning: 'hover:bg-warning hover:text-warning-foreground',
    danger: 'hover:bg-danger hover:text-danger-foreground',
    info: 'hover:bg-info hover:text-info-foreground',
    light: 'hover:bg-light hover:text-light-foreground',
    dark: 'hover:bg-dark hover:text-dark-foreground',
    accent: 'hover:bg-accent hover:text-accent-foreground',
    destructive: 'hover:bg-destructive hover:text-destructive-foreground',
    muted: 'hover:bg-muted hover:text-muted-foreground',
  };

  return colors[variant ?? 'primary'];
}

function getSpinnerClasses(variant: any) {
  const colors: Record<string, string> = {
    primary: 'bg-primary text-primary-foreground hover:bg-primary',
    secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary',
    success: 'bg-success text-success-foreground hover:bg-success',
    warning: 'bg-warning text-warning-foreground hover:bg-warning',
    danger: 'bg-danger text-danger-foreground hover:bg-danger',
    info: 'bg-info text-info-foreground hover:bg-info',
    light: 'bg-light text-light-foreground hover:bg-light',
    dark: 'bg-dark text-dark-foreground hover:bg-dark',
    accent: 'bg-accent text-accent-foreground hover:bg-accent',
    destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive',
    muted: 'bg-muted text-muted-foreground hover:bg-muted',
    link: 'text-primary',
  };

  return colors[variant ?? 'primary'];
}

function getOutlineSpinnerClasses(variant: any) {
  const colors: Record<string, string> = {
    primary: 'text-primary',
    secondary: 'text-secondary',
    success: 'text-success',
    warning: 'text-warning',
    danger: 'text-danger',
    info: 'text-info',
    light: 'text-light',
    dark: 'text-dark',
    accent: 'text-accent',
    destructive: 'text-destructive',
    muted: 'text-muted-foreground',
    link: 'text-primary',
  };

  return colors[variant ?? 'primary'];
}

function getThinClasses(size: any) {
  const colors: Record<string, string> = {
    default: 'h-8 px-2 py-1',
    sm: 'h-7 px-2 py-1',
    lg: 'h-9 px-2 py-1',
    icon: 'h-8 w-8',
  };

  return colors[size ?? 'default'];
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  (
    { className, variant, size, outline, outlineFilled, loading, thin, asChild = false, children, left, ...props },
    ref,
  ) => {
    const Comp = asChild ? Slot : 'button';

    let outlineClasses: string[] = [];
    if (outline || outlineFilled) {
      outlineClasses = ['bg-white border', getOutlineClasses(variant)];
      if (outlineFilled) outlineClasses.push(getOutlineFilledClasses(variant));
    }

    const thinClasses = thin ? getThinClasses(size) : '';

    if (loading) {
      const { ...loaderProps } = props;
      const spinnerClasses = outline || outlineFilled ? getOutlineSpinnerClasses(variant) : getSpinnerClasses(variant);
      const loadingClasses = 'pointer-events-none';

      return (
        <Comp
          type="button"
          className={cn(
            buttonVariants({ variant, size, outline, className }),
            outlineClasses,
            thinClasses,
            spinnerClasses,
            loadingClasses,
          )}
          ref={ref}
          {...loaderProps}
        >
          <div className="relative inline-flex items-center">
            <span className="invisible">{children}</span>
            <span className="absolute inset-0 flex items-center justify-center">
              <Spinner className={cn(spinnerClasses, loadingClasses)} />
            </span>
          </div>
        </Comp>
      );
    }

    return (
      <Comp
        type="button"
        className={cn(buttonVariants({ variant, size, outline, className }), outlineClasses, thinClasses)}
        ref={ref}
        {...props}
      >
        <div className="flex items-center gap-1">
          {left}
          {children}
        </div>
      </Comp>
    );
  },
);
Button.displayName = 'Button';

export { Button, buttonVariants };

// packages/angular/projects/button/src/lib/button.ts
import { Component, Input, computed, signal } from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import { BrnButton } from '@spartan-ng/brain/button';
import { EgSpinner } from '@egose/shadcn-theme-ng/spinner';
import { cva, type VariantProps } from 'class-variance-authority';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

function hlm(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const buttonVariants = cva(
  [
    'tw:cursor-pointer',
    'tw:active:translate-y-[0.5px]',
    'tw:disabled:pointer-events-none',
    'tw:disabled:opacity-50',
    'tw:focus-visible:outline-none',
    'tw:focus-visible:ring-1',
    'tw:focus-visible:ring-ring',
    'tw:font-medium',
    'tw:gap-2',
    'tw:inline-flex',
    'tw:items-center',
    'tw:justify-center',
    'tw:rounded-sm',
    'tw:text-sm',
    'tw:transform',
    'tw:transition',
    'tw:transition-colors',
    'tw:whitespace-nowrap',
    'tw:[&_svg]:pointer-events-none',
    'tw:[&_svg]:shrink-0',
    'tw:[&_svg]:size-4',
  ],
  {
    variants: {
      variant: {
        primary:
          'tw:border tw:border-primary tw:bg-primary tw:text-primary-foreground tw:shadow-sm tw:hover:bg-primary/90',
        secondary:
          'tw:border tw:border-secondary tw:bg-secondary tw:text-secondary-foreground tw:shadow-sm tw:hover:bg-secondary/90',
        success:
          'tw:border tw:border-success tw:bg-success tw:text-success-foreground tw:shadow-sm tw:hover:bg-success/90',
        warning:
          'tw:border tw:border-warning tw:bg-warning tw:text-warning-foreground tw:shadow-sm tw:hover:bg-warning/90',
        danger: 'tw:border tw:border-danger tw:bg-danger tw:text-danger-foreground tw:shadow-sm tw:hover:bg-danger/90',
        info: 'tw:border tw:border-info tw:bg-info tw:text-info-foreground tw:shadow-sm tw:hover:bg-info/90',
        light: 'tw:border tw:border-light tw:bg-light tw:text-light-foreground tw:shadow-sm tw:hover:bg-light/90',
        dark: 'tw:border tw:border-dark tw:bg-dark tw:text-dark-foreground tw:shadow-sm tw:hover:bg-dark/90',
        accent: 'tw:border tw:border-accent tw:bg-accent tw:text-accent-foreground tw:shadow-sm tw:hover:bg-accent/90',
        destructive:
          'tw:border tw:border-destructive tw:bg-destructive tw:text-destructive-foreground tw:shadow-sm tw:hover:bg-destructive/90',
        muted: 'tw:border tw:border-muted tw:bg-muted tw:text-muted-foreground tw:shadow-sm tw:hover:bg-muted/90',
        link: 'tw:text-primary tw:underline-offset-4 tw:hover:underline',
        ghost: 'tw:hover:bg-light tw:hover:text-light-foreground',
      },
      size: {
        default: 'tw:h-9 tw:px-4 tw:py-2',
        sm: 'tw:h-8 tw:rounded-sm tw:px-3 tw:text-xs',
        lg: 'tw:h-10 tw:rounded-sm tw:px-8',
        icon: 'tw:h-9 tw:w-9',
        'compact-default': 'tw:h-8 tw:px-2 tw:py-1',
        'compact-sm': 'tw:h-7 tw:px-2 tw:py-1',
        'compact-lg': 'tw:h-9 tw:px-2 tw:py-1',
        'compact-icon': 'tw:h-8 tw:w-8',
      },
      appearance: {
        solid: '',
        outline: 'tw:bg-white tw:border',
        outlineFilled: 'tw:bg-white tw:border',
      },
      loading: {
        true: 'tw:pointer-events-none',
        false: null,
      },
    },
    defaultVariants: {
      variant: 'primary',
      size: 'default',
      appearance: 'solid',
      loading: false,
    },
  },
);

export type ButtonVariants = VariantProps<typeof buttonVariants>;
export type VariantType = NonNullable<ButtonVariants['variant']>;
export type SizeType = NonNullable<ButtonVariants['size']>;
export type AppearanceType = NonNullable<ButtonVariants['appearance']>;

@Component({
  selector: 'button[egButton], a[egButton]',
  standalone: true,
  imports: [BrnButton, EgSpinner, NgTemplateOutlet],
  hostDirectives: [{ directive: BrnButton, inputs: ['disabled'] }],
  host: {
    '[class]': '_computedClass()',
    '[attr.aria-busy]': 'loading || null',
    '[attr.disabled]': '(loading || disabled) ? true : null',
  },
  template: `
    <ng-template #projected>
      <ng-content></ng-content>
    </ng-template>

    @if (loading) {
      <div class="tw:relative tw:inline-flex tw:items-center">
        <span class="tw:invisible">
          <ng-container *ngTemplateOutlet="projected" />
        </span>
        <span class="tw:absolute tw:inset-0 tw:flex tw:items-center tw:justify-center">
          <eg-spinner size="small" [spinnerClass]="spinnerClass()" />
        </span>
      </div>
    } @else {
      <div class="tw:flex tw:items-center tw:gap-1">
        @if (icon && iconPosition === 'left') {
          <ng-container *ngTemplateOutlet="icon" />
        }
        <ng-container *ngTemplateOutlet="projected" />
        @if (icon && iconPosition === 'right') {
          <ng-container *ngTemplateOutlet="icon" />
        }
      </div>
    }
  `,
})
export class EgButton {
  /** Props */
  @Input() variant: VariantType = 'primary';
  @Input() size: SizeType = 'default';
  @Input() appearance: AppearanceType = 'solid';
  @Input() loading = false;
  @Input() icon?: any;
  @Input() iconPosition: 'left' | 'right' = 'left';
  @Input() userClass: ClassValue = '';
  @Input() spinnerUserClass: ClassValue = '';
  @Input() disabled = false;

  private readonly _additionalClasses = signal<ClassValue>('');

  /** Computed button class merging */
  protected readonly _computedClass = computed(() => {
    const outlineClasses =
      this.appearance === 'outline' || this.appearance === 'outlineFilled'
        ? [this.getOutlineClasses(this.variant)]
        : [];
    if (this.appearance === 'outlineFilled') {
      outlineClasses.push(this.getOutlineFilledClasses(this.variant));
    }
    return hlm(
      buttonVariants({
        variant: this.variant,
        size: this.size,
        appearance: this.appearance,
        loading: this.loading,
        className: this.userClass,
      }),
      outlineClasses,
      this.loading ? 'tw:pointer-events-none' : '',
      this._additionalClasses(),
    );
  });

  /** Computed spinner classes */
  protected readonly spinnerClass = computed(() => {
    const base =
      this.appearance === 'outline' || this.appearance === 'outlineFilled'
        ? this.getOutlineSpinnerClasses(this.variant)
        : this.getSpinnerClasses(this.variant);
    return hlm(base, this.spinnerUserClass);
  });

  setClass(classes: string): void {
    this._additionalClasses.set(classes);
  }

  /** Helper functions */
  private getOutlineClasses(variant: VariantType) {
    const colors: Record<VariantType, string> = {
      primary: 'tw:border-primary tw:text-primary tw:shadow-sm tw:hover:bg-primary/10',
      secondary: 'tw:border-secondary tw:text-secondary tw:shadow-sm tw:hover:bg-secondary/10',
      success: 'tw:border-success tw:text-success tw:shadow-sm tw:hover:bg-success/10',
      warning: 'tw:border-warning tw:text-warning tw:shadow-sm tw:hover:bg-warning/10',
      danger: 'tw:border-danger tw:text-danger tw:shadow-sm tw:hover:bg-danger/10',
      info: 'tw:border-info tw:text-info tw:shadow-sm tw:hover:bg-info/10',
      light: 'tw:border-light tw:text-light-foreground tw:shadow-sm tw:hover:bg-light/10',
      dark: 'tw:border-dark tw:text-dark tw:shadow-sm tw:hover:bg-dark/10',
      accent: 'tw:border-accent tw:text-accent tw:shadow-sm tw:hover:bg-accent/10',
      destructive: 'tw:border-destructive tw:text-destructive tw:shadow-sm tw:hover:bg-destructive/10',
      muted: 'tw:border-muted tw:text-muted-foreground tw:shadow-sm tw:hover:bg-muted/10',
      link: 'tw:text-primary',
      ghost: 'tw:text-light-foreground',
    };
    return colors[variant];
  }

  private getOutlineFilledClasses(variant: VariantType) {
    const colors: Record<VariantType, string> = {
      primary: 'tw:hover:bg-primary tw:hover:text-primary-foreground',
      secondary: 'tw:hover:bg-secondary tw:hover:text-secondary-foreground',
      success: 'tw:hover:bg-success tw:hover:text-success-foreground',
      warning: 'tw:hover:bg-warning tw:hover:text-warning-foreground',
      danger: 'tw:hover:bg-danger tw:hover:text-danger-foreground',
      info: 'tw:hover:bg-info tw:hover:text-info-foreground',
      light: 'tw:hover:bg-light tw:hover:text-light-foreground',
      dark: 'tw:hover:bg-dark tw:hover:text-dark-foreground',
      accent: 'tw:hover:bg-accent tw:hover:text-accent-foreground',
      destructive: 'tw:hover:bg-destructive tw:hover:text-destructive-foreground',
      muted: 'tw:hover:bg-muted tw:hover:text-muted-foreground',
      link: 'tw:hover:underline',
      ghost: 'tw:hover:bg-light',
    };
    return colors[variant];
  }

  private getSpinnerClasses(variant: VariantType) {
    const colors: Record<VariantType, string> = {
      primary: 'tw:[&>svg]:text-primary-foreground',
      secondary: 'tw:[&>svg]:text-secondary-foreground',
      success: 'tw:[&>svg]:text-success-foreground',
      warning: 'tw:[&>svg]:text-warning-foreground',
      danger: 'tw:[&>svg]:text-danger-foreground',
      info: 'tw:[&>svg]:text-info-foreground',
      light: 'tw:[&>svg]:text-light-foreground',
      dark: 'tw:[&>svg]:text-dark-foreground',
      accent: 'tw:[&>svg]:text-accent-foreground',
      destructive: 'tw:[&>svg]:text-destructive-foreground',
      muted: 'tw:[&>svg]:text-muted-foreground',
      link: 'tw:[&>svg]:text-primary',
      ghost: 'tw:[&>svg]:text-light-foreground',
    };
    return colors[variant];
  }

  private getOutlineSpinnerClasses(variant: VariantType) {
    const colors: Record<VariantType, string> = {
      primary: 'tw:[&>svg]:text-primary',
      secondary: 'tw:[&>svg]:text-secondary',
      success: 'tw:[&>svg]:text-success',
      warning: 'tw:[&>svg]:text-warning',
      danger: 'tw:[&>svg]:text-danger',
      info: 'tw:[&>svg]:text-info',
      light: 'tw:[&>svg]:text-light',
      dark: 'tw:[&>svg]:text-dark',
      accent: 'tw:[&>svg]:text-accent',
      destructive: 'tw:[&>svg]:text-destructive',
      muted: 'tw:[&>svg]:text-muted-foreground',
      link: 'tw:[&>svg]:text-primary',
      ghost: 'tw:[&>svg]:text-light-foreground',
    };
    return colors[variant];
  }
}
