// packages/angular/@examples/standard/src/app/pages/components/toggle-group/toggle-group.ts
import { Component } from '@angular/core';
import { DemoHeaderComponent } from '../../../shared/demo-header';
import { HlmToggleGroup, HlmToggleGroupItem } from '@egose/shadcn-theme-ng/toggle-group';

@Component({
  selector: 'app-toggle-group-page',
  imports: [DemoHeaderComponent, HlmToggleGroup, HlmToggleGroupItem],
  template: `
    <app-demo-header title="Toggle Group" description="A set of two-state buttons." />
    <div hlmToggleGroup>
      <button hlmToggleGroupItem>Bold</button>
      <button hlmToggleGroupItem>Italic</button>
      <button hlmToggleGroupItem>Underline</button>
    </div>
  `,
})
export class ToggleGroupPage {}

// packages/react/@examples/nextjs/app/components/toggle-group/page.tsx
'use client';

import { ToggleGroup, ToggleGroupItem } from '@egose/shadcn-theme/components/ui/toggle-group';
import { Bold, Italic, Underline } from 'lucide-react';
import { ExamplePage, ExampleSection } from '@/components/showcase-shell';

export default function Page() {
  return (
    <ExamplePage
      title="Toggle Group"
      description="A set of two-state buttons for controlling formatting or selection options."
    >
      <ExampleSection
        title="Multiple Selection"
        description="Outline-styled group with bold, italic, and underline toggles."
      >
        <ToggleGroup variant="outline" type="multiple">
          <ToggleGroupItem value="bold" aria-label="Toggle bold">
            <Bold />
          </ToggleGroupItem>
          <ToggleGroupItem value="italic" aria-label="Toggle italic">
            <Italic />
          </ToggleGroupItem>
          <ToggleGroupItem value="strikethrough" aria-label="Toggle strikethrough">
            <Underline />
          </ToggleGroupItem>
        </ToggleGroup>
      </ExampleSection>
    </ExamplePage>
  );
}
