// packages/react/@examples/nextjs/app/components/badge/page.tsx
'use client';

import _startCase from 'lodash-es/startCase';
import { Badge } from '../../../../../components/ui/badge';

// All possible values from your badgeVariants definition
const variants = [
  'primary',
  'secondary',
  'success',
  'warning',
  'danger',
  'info',
  'light',
  'dark',
  'accent',
  'destructive',
  'muted',
  'link',
  'ghost',
] as const;

const sizes = ['sm', 'default', 'lg'] as const;
const appearances = ['solid', 'outline', 'outline-filled'] as const;

export default function Page() {
  return (
    <>
      <h1 className="font-bold text-2xl mt-4 mb-5">Badge Showcase</h1>

      {/* Variants x Appearance */}
      {appearances.map((appearance) => (
        <Section key={appearance} title={`Appearance: ${_startCase(appearance)}`}>
          {variants.map((variant) => (
            <Badge key={variant} variant={variant} appearance={appearance}>
              {_startCase(variant)}
            </Badge>
          ))}
        </Section>
      ))}

      {/* Sizes */}
      <Section title="Sizes">
        {sizes.map((size) => (
          <Badge key={size} size={size}>
            {_startCase(size)}
          </Badge>
        ))}
      </Section>

      {/* Variants x Sizes */}
      {sizes.map((size) => (
        <Section key={size} title={`Size: ${_startCase(size)}`}>
          {variants.map((variant) => (
            <Badge key={variant} variant={variant} size={size}>
              {_startCase(variant)}
            </Badge>
          ))}
        </Section>
      ))}
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="font-semibold mt-6">
      <h3 className="mb-2">{title}</h3>
      <div className="flex flex-wrap gap-2">{children}</div>
    </div>
  );
}

// apps/angular/src/app/pages/components/badge/badge.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { EgBadge, BadgeVariantType, BadgeSizeType, BadgeAppearanceType } from '@egose/shadcn-theme-ng/badge';

@Component({
  selector: 'app-badge-sample',
  standalone: true,
  imports: [CommonModule, EgBadge],
  template: `
    <div class="tw:space-y-8 tw:p-6">
      <h1 class="tw:text-2xl tw:font-bold">Badge Showcase</h1>

      <!-- Loop through appearances -->
      @for (appearance of appearances; track appearance) {
        <div class="tw:space-y-4">
          <h2 class="tw:text-xl tw:font-semibold">Appearance: {{ appearance }}</h2>

          <!-- Loop through sizes -->
          @for (size of sizes; track size) {
            <div>
              <h3 class="tw:font-medium tw:mb-2">Size: {{ size }}</h3>
              <div class="tw:flex tw:flex-wrap tw:gap-2">
                <!-- Loop through variants -->
                @for (variant of variants; track variant) {
                  <span egBadge [variant]="variant" [size]="size" [appearance]="appearance">
                    {{ variant }}
                  </span>
                }
              </div>
            </div>
          }
        </div>
      }
    </div>
  `,
})
export class Badgeage {
  variants: BadgeVariantType[] = [
    'primary',
    'secondary',
    'success',
    'warning',
    'danger',
    'info',
    'light',
    'dark',
    'accent',
    'destructive',
    'muted',
    'link',
    'ghost',
  ];

  sizes: BadgeSizeType[] = ['sm', 'default', 'lg'];

  appearances: BadgeAppearanceType[] = ['solid', 'outline', 'outline-filled'];
}
