// packages/react/@examples/nextjs/app/components/button/page.tsx
'use client';

import { IconInbox } from '@tabler/icons-react';
import _startCase from 'lodash-es/startCase';
import { Button } from '../../../../../components/ui/button';

// All possible values from your buttonVariants definition
const variants = [
  'primary',
  'secondary',
  'success',
  'warning',
  'danger',
  'info',
  'light',
  'dark',
  'link',
  'destructive',
  'accent',
  'muted',
] as const;

const sizes = [
  'xs',
  'sm',
  'default',
  'lg',
  'icon',
  'compact-xs',
  'compact-sm',
  'compact-default',
  'compact-lg',
] as const;

const appearances = ['solid', 'outline', 'outline-filled'] as const;

export default function Page() {
  return (
    <>
      <h1 className="font-bold text-2xl mt-4 mb-5">Button Showcase</h1>

      {/* Variants x Appearance x Loading */}
      {appearances.map((appearance) => (
        <Section key={appearance} title={`Appearance: ${_startCase(appearance)}`}>
          {variants.map((variant) => (
            <Button key={variant} variant={variant} appearance={appearance}>
              {_startCase(variant)}
            </Button>
          ))}
        </Section>
      ))}

      {/* Sizes */}
      <Section title="Sizes">
        {sizes.map((size) => (
          <Button key={size} size={size}>
            {_startCase(size)}
          </Button>
        ))}
      </Section>

      {/* Loading States */}
      {appearances.map((appearance) => (
        <Section key={appearance + '-loading'} title={`Appearance: ${_startCase(appearance)} - Loading`}>
          {variants.map((variant) => (
            <Button key={variant} variant={variant} appearance={appearance} loading>
              {_startCase(variant)}
            </Button>
          ))}
        </Section>
      ))}

      {/* Disabled States */}
      {appearances.map((appearance) => (
        <Section key={appearance + '-disabled'} title={`Appearance: ${_startCase(appearance)} - Disabled`}>
          {variants.map((variant) => (
            <Button key={variant} variant={variant} appearance={appearance} disabled>
              {_startCase(variant)}
            </Button>
          ))}
        </Section>
      ))}

      {/* Loading + Disabled */}
      {appearances.map((appearance) => (
        <Section
          key={appearance + '-loading-disabled'}
          title={`Appearance: ${_startCase(appearance)} - Loading + Disabled`}
        >
          {variants.map((variant) => (
            <Button key={variant} variant={variant} appearance={appearance} disabled loading>
              {_startCase(variant)}
            </Button>
          ))}
        </Section>
      ))}

      {/* Icons */}
      <Section title="Icons (Left)">
        {variants.map((variant) => (
          <Button key={variant + '-icon-left'} variant={variant} icon={<IconInbox />} iconPosition="left">
            {_startCase(variant)}
          </Button>
        ))}
      </Section>

      <Section title="Icons (Right)">
        {variants.map((variant) => (
          <Button key={variant + '-icon-right'} variant={variant} icon={<IconInbox />} iconPosition="right">
            {_startCase(variant)}
          </Button>
        ))}
      </Section>
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="font-semibold mt-6">
      <h3 className="mb-2">{title}</h3>
      <div className="flex flex-wrap gap-2">{children}</div>
    </div>
  );
}

// apps/angular/src/app/pages/components/button/button.ts
import { Component } from '@angular/core';
import { EgButton, AppearanceType, VariantType, SizeType } from '@egose/shadcn-theme-ng/button';
import { NgIcon } from '@ng-icons/core';
import { tablerBrandAngular } from '@ng-icons/tabler-icons';

@Component({
  selector: 'app-button',
  standalone: true,
  imports: [EgButton, NgIcon],
  template: `
    <div class="tw:space-y-8 tw:p-6">
      <h1 class="tw:text-2xl tw:font-bold">Button Showcase</h1>

      <ng-template #iconTemplate>
        <ng-icon [svg]="icon" />
      </ng-template>

      @for (section of sections; track section.title) {
        <div class="tw:font-semibold tw:mt-4">
          <h3>{{ section.title }}</h3>
          <div class="tw:flex tw:flex-wrap tw:gap-2">
            @for (v of variants; track v) {
              <button
                egButton
                [variant]="v"
                [appearance]="section.appearance ?? 'solid'"
                [size]="section.size ?? 'default'"
                [disabled]="section.disabled || false"
                [loading]="section.loading || false"
                [icon]="section.icon ? iconTemplate : null"
                [iconPosition]="section.iconPosition || 'left'"
              >
                {{ v }}
              </button>
            }
          </div>
        </div>
      }
    </div>
  `,
})
export class ButtonPage {
  icon = tablerBrandAngular;

  // Strongly typed variants
  variants: VariantType[] = [
    'primary',
    'secondary',
    'success',
    'warning',
    'danger',
    'info',
    'light',
    'dark',
    'link',
    'destructive',
    'accent',
    'muted',
  ];

  sections: {
    title: string;
    appearance?: AppearanceType;
    size?: SizeType;
    disabled?: boolean;
    loading?: boolean;
    icon?: boolean;
    iconPosition?: 'left' | 'right';
  }[] = [
    { title: 'Basic' },
    { title: 'Basic - disabled', disabled: true },
    { title: 'Basic - loading', loading: true },
    { title: 'Basic - disabled - loading', disabled: true, loading: true },
    { title: 'Basic - compact', size: 'compact-default' },

    { title: 'Outline', appearance: 'outline' },
    { title: 'Outline - disabled', appearance: 'outline', disabled: true },
    { title: 'Outline - loading', appearance: 'outline', loading: true },
    { title: 'Outline - disabled - loading', appearance: 'outline', disabled: true, loading: true },
    { title: 'Outline - compact', appearance: 'outline', size: 'compact-default' },

    { title: 'Outline filled', appearance: 'outline-filled' },
    { title: 'Outline filled - disabled', appearance: 'outline-filled', disabled: true },
    { title: 'Outline filled - loading', appearance: 'outline-filled', loading: true },
    { title: 'Outline filled - disabled - loading', appearance: 'outline-filled', disabled: true, loading: true },
    { title: 'Outline filled - compact', appearance: 'outline-filled', size: 'compact-default' },

    { title: 'Icon (left)', icon: true, iconPosition: 'left' },
    { title: 'Icon (right)', icon: true, iconPosition: 'right' },
  ];
}
