// devapp/app/components/button/page.tsx
'use client';

import { IconInbox } from '@tabler/icons-react';
import _startCase from 'lodash-es/startCase';
import { Button } from '../../../../package/components/ui/button';

const variants = [
  'primary',
  'secondary',
  'success',
  'warning',
  'danger',
  'info',
  'light',
  'dark',
  'link',
  'destructive',
  'accent',
  'muted',
] as const;

export default function Page() {
  return (
    <>
      <h1 className="font-bold text-2xl mt-4 mb-5">Button</h1>

      <div className="font-semibold">
        <h3>Basic</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant}>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Basic - disabled</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} disabled>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Basic - loading</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} loading>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Basic - disabled - loading</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} disabled loading>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Basic - thin</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} thin>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Outline</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} outline>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Outline - disabled</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} outline disabled>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Outline - loading</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} outline loading>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Outline - disabled - loading</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} outline disabled loading>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Outline - thin</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} outline thin>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Outline filled</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} outlineFilled>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Outline filled - disabled</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} outlineFilled disabled>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Outline filled - loading</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} outlineFilled loading>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Outline filled - disabled - loading</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} outlineFilled disabled loading>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Outline filled - thin</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} outlineFilled thin>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>

      <div className="font-semibold mt-4">
        <h3>Icon</h3>
        <div className="flex gap-2">
          {variants.map((variant) => {
            return (
              <Button key={variant} variant={variant} left={<IconInbox />}>
                {_startCase(variant)}
              </Button>
            );
          })}
        </div>
      </div>
    </>
  );
}

// apps/angular/src/app/pages/components/button/button.ts
import { Component } from '@angular/core';
import { EgButton } from '@egose/shadcn-theme-ng/button';
import { NgIcon } from '@ng-icons/core';
import { tablerBrandAngular } from '@ng-icons/tabler-icons';

@Component({
  selector: 'app-button',
  standalone: true,
  imports: [EgButton, NgIcon],
  template: `
    <h1 class="font-bold text-2xl mt-4 mb-5">Button</h1>

    <ng-template #lefticon>
      <ng-icon [svg]="icon" />
    </ng-template>

    @for (section of sections; track section.title) {
      <div class="font-semibold mt-4">
        <h3>{{ section.title }}</h3>
        <div class="flex gap-2">
          @for (v of variants; track v) {
            <button
              egBtn
              [variant]="v"
              [disabled]="section.disabled"
              [loading]="section.loading ?? false"
              [compact]="section.compact ?? false"
              [outline]="section.outline ?? false"
              [outlineFilled]="section.outlineFilled ?? false"
              [left]="section.icon ? lefticon : ''"
            >
              {{ v }}
            </button>
          }
        </div>
      </div>
    }
  `,
})
export class ButtonPage {
  icon = tablerBrandAngular;

  variants = [
    'primary',
    'secondary',
    'success',
    'warning',
    'danger',
    'info',
    'light',
    'dark',
    'link',
    'destructive',
    'accent',
    'muted',
  ] as const;

  sections = [
    { title: 'Basic' },
    { title: 'Basic - disabled', disabled: true },
    { title: 'Basic - loading', loading: true },
    { title: 'Basic - disabled - loading', disabled: true, loading: true },
    { title: 'Basic - compact', compact: true },
    { title: 'Outline', outline: true },
    { title: 'Outline - disabled', outline: true, disabled: true },
    { title: 'Outline - loading', outline: true, loading: true },
    { title: 'Outline - disabled - loading', outline: true, disabled: true, loading: true },
    { title: 'Outline - compact', outline: true, compact: true },
    { title: 'Outline filled', outlineFilled: true },
    { title: 'Outline filled - disabled', outlineFilled: true, disabled: true },
    { title: 'Outline filled - loading', outlineFilled: true, loading: true },
    { title: 'Outline filled - disabled - loading', outlineFilled: true, disabled: true, loading: true },
    { title: 'Outline filled - compact', outlineFilled: true, compact: true },
    { title: 'Icon', icon: true },
  ];
}
